services:

  server:
    container_name: maxitwitserver
    build:
      dockerfile: Dockerfile.app
      context: .
      target: production
    volumes:
      - ./db:/usr/src/app/db
      - ./src:/usr/src/app/src
    ports:
      - 3000:3000
    networks:
      - itu-minitwit-network
    environment:
      - HUSKY=0
      - DATABASE_URL=file:../db/minitwit.db

  api:
    build:
      dockerfile: Dockerfile.api
      context: .
      target: production
    volumes:
      - ./db:/usr/src/app/db
      - ./src:/usr/src/app/src
    ports:
      - 3001:3000
    networks:
      - itu-minitwit-network
    environment:
      - HUSKY=0
      - DATABASE_URL=file:../db/minitwit.db

networks:
  itu-minitwit-network:
    name: itu-minitwit-network
