# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose

services:
  server:
    container_name: maxitwit-server
    build:
      dockerfile: Dockerfile.app
      context: .
      target: ${TARGET}
    volumes:
      - ./db:/usr/src/app/db
      - ./src:/usr/src/app/src
    ports:
      - 3000:3000
    networks:
      - itu-minitwit-network
    environment:
      - HUSKY=0
    env_file: .env
  
  api:
    container_name: maxitwit-api
    build:
      dockerfile: Dockerfile.api
      context: .
      target: ${TARGET}
    volumes:
      - ./db:/usr/src/app/db
      - ./src:/usr/src/app/src
    ports:
      - 3001:3000
    networks:
      - itu-minitwit-network
    environment:
      - HUSKY=0
    env_file: .env

networks:
  itu-minitwit-network:
    name: itu-minitwit-network