services:
  server:
    image: ${DOCKER_USERNAME}/maxitwit-server
    volumes:
      - ../db:/usr/src/app/db
      - ../src:/usr/src/app/src
    ports:
      - 3000:3000
    networks:
      - maxitwit-network
    environment:
      - HUSKY=0
      - DATABASE_URL=file:../db/minitwit.db
      - SESSION_SECRET=${SESSION_SECRET}
      - TARGET=prod

  api:
    image: ${DOCKER_USERNAME}/maxitwit-api
    volumes:
      - ../db:/usr/src/app/db
      - ../src:/usr/src/app/src
    ports:
      - 3001:3000
    networks:
      - maxitwit-network
    environment:
      - HUSKY=0
      - DATABASE_URL=file:../db/minitwit.db
      - SESSION_SECRET=${SESSION_SECRET}
      - TARGET=prod
      
networks:
  maxitwit-network:
    name: maxitwit-network